services:
  frontend:
    image: docs:frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

  backend:
    image: docs:backend
    user: "${DUID}:${DGID}"
    volumes:
      - ./db:/app/db
      - ./docs:/app/docs
